version: '3.8'

services:
    # BackendAPI
    smartbrain-api:
        container_name: backend
        build: ./
        command: npm run dev
        working_dir: /usr/src/smartbrainAPI
        environment: 
            DATABASE_URL: postgres://sally:secret@postgres:5432/smartbrain-docker
            REDIS_URL: redis://redis:6379
        ports: 
            - '3000:3000'
        volumes: 
            - ./:/usr/src/smartbrainAPI
    # Postgres
    postgres:
        build: ./postgres
        ports: 
            - '5432:5432'
        environment: 
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smartbrain-docker
            POSTGRES_HOST: postgres
    # Redis
    redis:
        image: redis
        ports: 
            - "6379:6379"
        